version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: on-failure:10
  server:
    build: ./server
    depends_on:
      - nginx
    expose:
      - "5000"
    restart: on-failure:10
